const importedClients=[
{id:'sbis-0326022560',name:'ООО «Байкалприбор+»',inn:'0326022560',kpp:'032601001',contractNumber:'18',contractDate:'2025-01-01'},
{id:'sbis-032627912104',name:'ИП Бородин Антон Александрович',inn:'032627912104',kpp:'',contractNumber:'2-2026',contractDate:'2026-01-01'},
{id:'sbis-0326029510',name:'ГК №233',inn:'0326029510',kpp:'032601001',contractNumber:'24',contractDate:'2026-03-24'},
{id:'sbis-032315097535',name:'ИП Гоголадзе Руслан Нугзариевич',inn:'032315097535',kpp:'',contractNumber:'11',contractDate:'2025-08-29'},
{id:'sbis-032616652849',name:'ИП Зурбулаев Сергей Васильевич',inn:'032616652849',kpp:'',contractNumber:'26',contractDate:'2026-03-24'},
{id:'sbis-032602369278',name:'ИП Ивлев Артемий Сергеевич',inn:'032602369278',kpp:'',contractNumber:'15',contractDate:'2025-08-29'},
{id:'sbis-032605197700',name:'ИП Кушнарев Константин Владимирович',inn:'032605197700',kpp:'',contractNumber:'28',contractDate:'2026-03-24'},
{id:'sbis-032624508528',name:'ИП Медведев Денис Дмитриевич',inn:'032624508528',kpp:'',contractNumber:'9',contractDate:'2025-08-20'},
{id:'sbis-253702176738',name:'ИП Орлова Ольга Андреяновна',inn:'253702176738',kpp:'',contractNumber:'16',contractDate:'2025-08-29'},
{id:'sbis-3812116741',name:'ООО «Пиком»',inn:'3812116741',kpp:'381201001',contractNumber:'25',contractDate:'2026-03-24'},
{id:'sbis-030953504540',name:'ИП Подолинчук Антон Васильевич',inn:'030953504540',kpp:'',contractNumber:'10',contractDate:'2025-08-25'},
{id:'sbis-0326008397',name:'ООО «Сибирское СПК»',inn:'0326008397',kpp:'503201001',contractNumber:'19',contractDate:'2025-07-03'},
{id:'sbis-0323399449',name:'ООО «СК Байкал-Констрактинг»',inn:'0323399449',kpp:'032601001',contractNumber:'21',contractDate:'2025-01-01'},
{id:'sbis-030678359861',name:'ИП Сокольников Дмитрий Андреевич',inn:'030678359861',kpp:'',contractNumber:'22',contractDate:'2026-01-12'},
{id:'sbis-0300013755',name:'ООО «СПК Сарма»',inn:'0300013755',kpp:'030001001',contractNumber:'1',contractDate:'2024-04-01'},
{id:'sbis-030402588832',name:'ИП Тумуров Роман Сергеевич',inn:'030402588832',kpp:'',contractNumber:'14',contractDate:'2025-08-29'},
{id:'sbis-772772521968',name:'ИП Уланова Елена Владимировна',inn:'772772521968',kpp:'',contractNumber:'17',contractDate:'2025-09-08'},
{id:'sbis-0326482832',name:'ООО ЧОП «Дивизион»',inn:'0326482832',kpp:'032301001',contractNumber:'20',contractDate:'2025-01-31'},
{id:'sbis-032312420412',name:'ИП Шаманский Владимир Георгиевич',inn:'032312420412',kpp:'',contractNumber:'27',contractDate:'2026-03-24'},
{id:'sbis-032617146612',name:'ИП Шаракшанэ Михаил Юрьевич',inn:'032617146612',kpp:'',contractNumber:'29',contractDate:'2026-07-06'},
{id:'sbis-032630244168',name:'ИП Шматкова Анастасия Олеговна',inn:'032630244168',kpp:'',contractNumber:'13',contractDate:'2025-08-29'},
{id:'sbis-032619630650',name:'ИП Шомоев Владислав Аркадьевич',inn:'032619630650',kpp:'',contractNumber:'12',contractDate:'2025-08-29'}
].map(c=>({...c,tax:'Не заполнено',accountant:'Не назначен',status:'В работе',source:'СБИС'}));
const defaultChecklist=['Выписка банка','Кассовые документы','Реализация','Покупки','Табель','Путевые листы','Авансовые отчеты','Акты сверки'];
const todayIso=()=>new Date().toISOString().slice(0,10);
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const norm=v=>String(v||'').toLowerCase().replace(/[«»"'.,]/g,'').replace(/\s+/g,' ').trim();
function mergeClients(saved){const out=[...(Array.isArray(saved)?saved:[])];importedClients.forEach(x=>{let e=out.find(c=>(c.inn&&c.inn===x.inn)||(!c.inn&&norm(c.name)===norm(x.name)));if(e)Object.entries(x).forEach(([k,v])=>{if(!e[k]||['Не заполнено','Не назначен'].includes(e[k]))e[k]=v});else out.push(x)});return out.map(c=>({...c,checklist:Array.isArray(c.checklist)?c.checklist:defaultChecklist.map((name,i)=>({id:i+1,name,status:'missing'})),knowledge:Array.isArray(c.knowledge)?c.knowledge:[],history:Array.isArray(c.history)?c.history:[],documents:Array.isArray(c.documents)?c.documents:[]}))}
const state={clients:mergeClients(load('nv_clients',[])),tasks:load('nv_tasks',[]),rules:load('nv_rules',[{id:1,title:'Электронная подпись',description:'Срок 13 месяцев. Напомнить заранее.'},{id:2,title:'Оплата налогов',description:'Срок 28 числа с учетом рабочих дней.'}]),activeClientId:null};
state.tasks=state.tasks.map(t=>({...t,dueDate:t.dueDate||'',dueTime:t.dueTime||'',status:t.status||(t.done?'done':'new'),history:Array.isArray(t.history)?t.history:[]}));
function save(){localStorage.setItem('nv_clients',JSON.stringify(state.clients));localStorage.setItem('nv_tasks',JSON.stringify(state.tasks));localStorage.setItem('nv_rules',JSON.stringify(state.rules))}
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const fmt=d=>d?new Intl.DateTimeFormat('ru-RU').format(new Date(d+'T00:00:00')):'—';
const titles={today:['Сегодня','Что требует внимания прямо сейчас'],clients:['Клиенты','Единый список клиентов'],tasks:['Задачи','Сроки, приоритеты и выполнение'],rules:['Правила','Повторяющиеся события и напоминания'],'client-card':['Карточка клиента','Рабочее место по клиенту']};
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.getElementById(id).classList.add('active');document.getElementById('page-title').textContent=titles[id][0];document.getElementById('page-subtitle').textContent=id==='clients'?`${state.clients.length} клиентов`:titles[id][1];renderAll()}
window.showPage=showPage;document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function renderToday(){const a=state.tasks.filter(t=>!t.done);document.getElementById('critical-count').textContent=a.filter(t=>t.priority==='critical').length;document.getElementById('high-count').textContent=a.filter(t=>t.priority==='high').length;document.getElementById('deferred-count').textContent=a.filter(t=>t.priority==='deferred'||t.status==='waiting').length;document.getElementById('done-count').textContent=state.tasks.filter(t=>t.done).length;document.getElementById('today-list').innerHTML=a.slice(0,6).map(taskHtml).join('')||'<p class="meta">Срочных задач нет</p>';document.getElementById('reminder-list').innerHTML=state.rules.map(r=>`<div class="rule-card"><b>${esc(r.title)}</b><div class="meta">${esc(r.description)}</div></div>`).join('')}
function taskHtml(t){return `<div class="task-item ${t.done?'done':''}"><div><b>${esc(t.title)}</b><div class="meta">${esc(t.client||'Без клиента')} · ${fmt(t.dueDate)} ${esc(t.dueTime||'')}</div></div><div><span class="badge ${t.done?'done':t.priority}">${t.done?'Выполнено':t.priority==='critical'?'Критично':t.priority==='high'?'Высокий':'Отложено'}</span><div style="margin-top:8px"><button class="link-btn" onclick="editTask('${t.id}')">Изменить</button><button class="link-btn" onclick="toggleTask('${t.id}')">${t.done?'Вернуть':'Готово'}</button></div></div></div>`}
function renderTasks(){const f=document.getElementById('task-filter')?.value||'all';const rows=state.tasks.filter(t=>f==='all'||(f==='done'?t.done:!t.done&&t.priority===f));document.getElementById('tasks-list').innerHTML=rows.map(taskHtml).join('')||'<p class="meta">Задач нет</p>'}
function renderClients(){const q=(document.getElementById('client-search')?.value||'').toLowerCase();const rows=state.clients.filter(c=>[c.name,c.inn,c.kpp,c.accountant,c.tax].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'ru'));document.getElementById('clients-list').innerHTML=rows.map(c=>`<div class="client-row" onclick="openClient('${c.id}')"><div><b>${esc(c.name)}</b><div class="meta">ИНН ${esc(c.inn||'—')}${c.kpp?' · КПП '+esc(c.kpp):''}</div></div><div><b>Договор №${esc(c.contractNumber||'—')}</b><div class="meta">от ${fmt(c.contractDate)}</div></div><div>${esc(c.accountant)}</div><div>${esc(c.status)}</div></div>`).join('')||'<p class="meta">Клиенты не найдены</p>'}
function renderRules(){document.getElementById('rules-list').innerHTML=state.rules.map(r=>`<article class="rule-card"><b>${esc(r.title)}</b><div class="meta">${esc(r.description)}</div></article>`).join('')}
function openClient(id){state.activeClientId=id;showPage('client-card')}window.openClient=openClient;
function renderClientCard(){const root=document.getElementById('client-card-content');if(!root)return;const c=state.clients.find(x=>String(x.id)===String(state.activeClientId));if(!c){root.innerHTML='<div class="empty-state">Клиент не выбран</div>';return}const ct=state.tasks.filter(t=>norm(t.client)===norm(c.name));const got=c.checklist.filter(x=>x.status==='received'||x.status==='not-needed').length;const pct=Math.round(got/c.checklist.length*100)||0;root.innerHTML=`
<div class="client-head"><div class="client-head-top"><div class="client-title"><h2>${esc(c.name)}</h2><p>ИНН ${esc(c.inn||'—')}${c.kpp?' · КПП '+esc(c.kpp):''}</p></div><div><button class="secondary" onclick="editClient('${c.id}')">Редактировать</button><button class="primary" onclick="newTaskForClient('${c.id}')">+ Задача</button></div></div><div class="client-summary"><div class="summary-box"><span>Статус</span><strong>${esc(c.status)}</strong></div><div class="summary-box"><span>Ответственный</span><strong>${esc(c.accountant)}</strong></div><div class="summary-box"><span>СНО</span><strong>${esc(c.tax)}</strong></div><div class="summary-box"><span>Документы</span><strong>${pct}% готово</strong></div></div></div>
<div class="client-tabs">${['overview','checklist','tasks','documents','knowledge','history'].map((x,i)=>`<button class="client-tab ${i===0?'active':''}" data-tab="${x}" onclick="switchClientTab('${x}',this)">${({overview:'Обзор',checklist:'Чек-лист',tasks:'Задачи',documents:'Документы',knowledge:'База знаний',history:'История'})[x]}</button>`).join('')}</div>
<div class="client-panel active" id="cp-overview"><section class="card"><div class="card-head"><h3>Общая информация</h3></div><div class="info-grid"><div class="info-item"><span>Наименование</span><b>${esc(c.name)}</b></div><div class="info-item"><span>ИНН / КПП</span><b>${esc(c.inn||'—')} / ${esc(c.kpp||'—')}</b></div><div class="info-item"><span>Договор</span><b>№ ${esc(c.contractNumber||'—')} от ${fmt(c.contractDate)}</b></div><div class="info-item"><span>Источник</span><b>${esc(c.source||'Ручной ввод')}</b></div><div class="info-item"><span>Ответственный бухгалтер</span><b>${esc(c.accountant)}</b></div><div class="info-item"><span>Стоимость обслуживания</span><b>${c.servicePrice?Number(c.servicePrice).toLocaleString('ru-RU')+' ₽':'Не заполнено'}</b></div></div></section></div>
<div class="client-panel" id="cp-checklist"><section class="card"><div class="card-head"><h3>Документы за текущий период</h3><b>${pct}%</b></div><div class="check-progress"><i style="width:${pct}%"></i></div>${c.checklist.map(x=>`<div class="check-row"><b>${esc(x.name)}</b><select onchange="setChecklistStatus('${c.id}',${x.id},this.value)"><option value="missing" ${x.status==='missing'?'selected':''}>Отсутствует</option><option value="requested" ${x.status==='requested'?'selected':''}>Запрошено</option><option value="received" ${x.status==='received'?'selected':''}>Получено</option><option value="not-needed" ${x.status==='not-needed'?'selected':''}>Не требуется</option></select>${x.status==='missing'?`<button class="link-btn" onclick="createChecklistTask('${c.id}',${x.id})">Создать задачу</button>`:''}</div>`).join('')}</section></div>
<div class="client-panel" id="cp-tasks"><section class="card"><div class="card-head"><h3>Задачи клиента</h3><button class="primary" onclick="newTaskForClient('${c.id}')">+ Задача</button></div>${ct.map(taskHtml).join('')||'<div class="empty-state">Задач пока нет</div>'}</section></div>
<div class="client-panel" id="cp-documents"><section class="card"><div class="card-head"><h3>Документы и договоры</h3><button class="primary" onclick="addDocument('${c.id}')">+ Документ</button></div><div class="document-row"><b>Договор №${esc(c.contractNumber||'—')}</b><div class="meta">Дата: ${fmt(c.contractDate)}</div></div>${c.documents.map(d=>`<div class="document-row"><b>${esc(d.title)}</b><div class="meta">${esc(d.comment||'')}</div></div>`).join('')}</section></div>
<div class="client-panel" id="cp-knowledge"><section class="card"><div class="card-head"><h3>База знаний клиента</h3><button class="primary" onclick="addKnowledge('${c.id}')">+ Запись</button></div>${c.knowledge.map(n=>`<div class="knowledge-note">${esc(n.text)}</div>`).join('')||'<div class="empty-state">Особенности клиента пока не записаны</div>'}</section></div>
<div class="client-panel" id="cp-history"><section class="card"><h3>История работы</h3>${[...c.history].reverse().map(h=>`<div class="history-row"><time>${new Date(h.at).toLocaleString('ru-RU')}</time>${esc(h.text)}</div>`).join('')||'<div class="empty-state">История пока пуста</div>'}</section></div>`}
function switchClientTab(tab,btn){document.querySelectorAll('.client-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.client-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('cp-'+tab).classList.add('active')}window.switchClientTab=switchClientTab;
function setChecklistStatus(cid,i,status){const c=state.clients.find(x=>String(x.id)===String(cid));const item=c?.checklist.find(x=>x.id===i);if(item){item.status=status;c.history.push({at:new Date().toISOString(),text:`Документ «${item.name}»: ${status}`});save();renderClientCard()}}window.setChecklistStatus=setChecklistStatus;
function createChecklistTask(cid,i){const c=state.clients.find(x=>String(x.id)===String(cid));const item=c?.checklist.find(x=>x.id===i);if(!item)return;state.tasks.push({id:Date.now(),title:`Запросить: ${item.name}`,client:c.name,priority:'high',dueDate:todayIso(),dueTime:'',status:'new',done:false,history:[]});item.status='requested';c.history.push({at:new Date().toISOString(),text:`Создана задача по документу «${item.name}»`});save();renderClientCard()}window.createChecklistTask=createChecklistTask;
function addKnowledge(cid){const c=state.clients.find(x=>String(x.id)===String(cid));const text=prompt('Введите особенность или комментарий по клиенту');if(c&&text){c.knowledge.push({id:Date.now(),text});c.history.push({at:new Date().toISOString(),text:'Добавлена запись в базу знаний'});save();renderClientCard()}}window.addKnowledge=addKnowledge;
function addDocument(cid){const c=state.clients.find(x=>String(x.id)===String(cid));const title=prompt('Название документа');if(c&&title){const comment=prompt('Комментарий к документу')||'';c.documents.push({id:Date.now(),title,comment});c.history.push({at:new Date().toISOString(),text:`Добавлен документ «${title}»`});save();renderClientCard()}}window.addDocument=addDocument;
function newTaskForClient(cid){const c=state.clients.find(x=>String(x.id)===String(cid));openTaskModal(null,c?.name||'')}window.newTaskForClient=newTaskForClient;
window.toggleTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t){t.done=!t.done;t.status=t.done?'done':'new';save();renderAll()}};
const modal=document.getElementById('modal'),form=document.getElementById('modal-form');
function closeModal(){modal.classList.remove('open')}window.closeModal=closeModal;document.getElementById('close-modal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
function openTaskModal(entity=null,clientName=''){modal.classList.add('open');document.getElementById('modal-title').textContent=entity?'Редактирование задачи':'Новая задача';form.innerHTML=`<div class="field"><label>Задача</label><input name="title" required value="${esc(entity?.title||'')}"></div><div class="field"><label>Клиент</label><input name="client" value="${esc(entity?.client||clientName)}"></div><div class="field"><label>Приоритет</label><select name="priority"><option value="critical">Критично</option><option value="high">Высокий</option><option value="deferred">Отложено</option></select></div><div class="field"><label>Дата исполнения</label><input type="date" name="dueDate" value="${entity?.dueDate||todayIso()}"></div><div class="field"><label>Время</label><input type="time" name="dueTime" value="${entity?.dueTime||''}"></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);if(entity)Object.assign(entity,{title:d.get('title'),client:d.get('client'),priority:d.get('priority'),dueDate:d.get('dueDate'),dueTime:d.get('dueTime')});else state.tasks.push({id:Date.now(),title:d.get('title'),client:d.get('client'),priority:d.get('priority'),dueDate:d.get('dueDate'),dueTime:d.get('dueTime'),status:'new',done:false,history:[]});save();closeModal();renderAll()}}
window.editTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t)openTaskModal(t)};
function editClient(id){const c=state.clients.find(x=>String(x.id)===String(id));if(!c)return;modal.classList.add('open');document.getElementById('modal-title').textContent='Редактирование клиента';form.innerHTML=`<div class="field"><label>Наименование</label><input name="name" value="${esc(c.name)}"></div><div class="field"><label>СНО</label><input name="tax" value="${esc(c.tax)}"></div><div class="field"><label>Ответственный</label><input name="accountant" value="${esc(c.accountant)}"></div><div class="field"><label>Стоимость обслуживания</label><input type="number" name="servicePrice" value="${esc(c.servicePrice||'')}"></div><div class="field"><label>Статус</label><select name="status"><option>В работе</option><option>Новый</option><option>Приостановлен</option><option>Расторгнут</option></select></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);Object.assign(c,{name:d.get('name'),tax:d.get('tax'),accountant:d.get('accountant'),servicePrice:d.get('servicePrice'),status:d.get('status')});c.history.push({at:new Date().toISOString(),text:'Карточка клиента отредактирована'});save();closeModal();renderClientCard()}}window.editClient=editClient;
function renderAll(){renderToday();renderTasks();renderClients();renderRules();renderClientCard()}
document.getElementById('client-search').oninput=renderClients;document.getElementById('task-filter').onchange=renderTasks;document.getElementById('quick-add').onclick=()=>openTaskModal();document.getElementById('add-task').onclick=()=>openTaskModal();document.getElementById('add-client').onclick=()=>editClient({});document.getElementById('add-rule').onclick=()=>alert('Добавление правил будет в следующем обновлении');document.getElementById('back-to-clients').onclick=()=>showPage('clients');
save();renderAll();