const importedClients = [
  {id:'sbis-0326022560',name:'ООО «Байкалприбор+»',inn:'0326022560',kpp:'032601001',contractNumber:'18',contractDate:'2025-01-01'},
  {id:'sbis-032627912104',name:'ИП Бородин Антон Александрович',inn:'032627912104',kpp:'',contractNumber:'2-2026',contractDate:'2026-01-01'},
  {id:'sbis-0326029510',name:'ГК №233',inn:'0326029510',kpp:'032601001',contractNumber:'24',contractDate:'2026-03-24'},
  {id:'sbis-032315097535',name:'ИП Гоголадзе Руслан Нугзариевич',inn:'032315097535',kpp:'',contractNumber:'11',contractDate:'2025-08-29'},
  {id:'sbis-032616652849',name:'ИП Зурбулаев Сергей Васильевич',inn:'032616652849',kpp:'',contractNumber:'26',contractDate:'2026-03-24'},
  {id:'sbis-032602369278',name:'ИП Ивлев Артемий Сергеевич',inn:'032602369278',kpp:'',contractNumber:'15',contractDate:'2025-08-29'},
  {id:'sbis-032605197700',name:'ИП Кушнарев Константин Владимирович',inn:'032605197700',kpp:'',contractNumber:'28',contractDate:'2026-03-24'},
  {id:'sbis-032624508528',name:'ИП Медведев Денис Дмитриевич',inn:'032624508528',kpp:'',contractNumber:'9',contractDate:'2025-08-20'},
  {id:'sbis-253702176738',name:'ИП Орлова Ольга Андреяновна',inn:'253702176738',kpp:'',contractNumber:'16',contractDate:'2025-08-29'},
  {id:'sbis-3812116741',name:'ООО «Пиком»',inn:'3812116741',kpp:'381201001',contractNumber:'25',contractDate:'2026-03-24'},
  {id:'sbis-030953504540',name:'ИП Подолинчук Антон Васильевич',inn:'030953504540',kpp:'',contractNumber:'10',contractDate:'2025-08-25'},
  {id:'sbis-0326008397',name:'ООО «Сибирское СПК»',inn:'0326008397',kpp:'503201001',contractNumber:'19',contractDate:'2025-07-03'},
  {id:'sbis-0323399449',name:'ООО «СК Байкал-Констрактинг»',inn:'0323399449',kpp:'032601001',contractNumber:'21',contractDate:'2025-01-01'},
  {id:'sbis-030678359861',name:'ИП Сокольников Дмитрий Андреевич',inn:'030678359861',kpp:'',contractNumber:'22',contractDate:'2026-01-12'},
  {id:'sbis-0300013755',name:'ООО «СПК Сарма»',inn:'0300013755',kpp:'030001001',contractNumber:'1',contractDate:'2024-04-01'},
  {id:'sbis-030402588832',name:'ИП Тумуров Роман Сергеевич',inn:'030402588832',kpp:'',contractNumber:'14',contractDate:'2025-08-29'},
  {id:'sbis-772772521968',name:'ИП Уланова Елена Владимировна',inn:'772772521968',kpp:'',contractNumber:'17',contractDate:'2025-09-08'},
  {id:'sbis-0326482832',name:'ООО ЧОП «Дивизион»',inn:'0326482832',kpp:'032301001',contractNumber:'20',contractDate:'2025-01-31'},
  {id:'sbis-032312420412',name:'ИП Шаманский Владимир Георгиевич',inn:'032312420412',kpp:'',contractNumber:'27',contractDate:'2026-03-24'},
  {id:'sbis-032617146612',name:'ИП Шаракшанэ Михаил Юрьевич',inn:'032617146612',kpp:'',contractNumber:'29',contractDate:'2026-07-06'},
  {id:'sbis-032630244168',name:'ИП Шматкова Анастасия Олеговна',inn:'032630244168',kpp:'',contractNumber:'13',contractDate:'2025-08-29'},
  {id:'sbis-032619630650',name:'ИП Шомоев Владислав Аркадьевич',inn:'032619630650',kpp:'',contractNumber:'12',contractDate:'2025-08-29'}
].map(c=>({...c,tax:'Не заполнено',accountant:'Не назначен',status:'В работе',source:'СБИС'}));

function todayIso(){return new Date().toISOString().slice(0,10)}
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function mergeClients(saved){
  const result=[...(Array.isArray(saved)?saved:[])];
  importedClients.forEach(item=>{
    const existing=result.find(c=>(c.inn&&c.inn===item.inn)||(!c.inn&&normalizeName(c.name)===normalizeName(item.name)));
    if(existing){Object.entries(item).forEach(([k,v])=>{if(!existing[k]||existing[k]==='Не заполнено'||existing[k]==='Не назначен')existing[k]=v});}
    else result.push(item);
  });
  return result;
}
function normalizeName(v=''){return String(v).toLowerCase().replace(/[«»"'.,]/g,'').replace(/\s+/g,' ').trim()}

const state={
  clients:mergeClients(load('nv_clients',[])),
  tasks:load('nv_tasks',[
    {id:1,title:'Проверить декларацию по налогу на прибыль',client:'ООО «СК Байкал-Констрактинг»',priority:'critical',dueDate:todayIso(),dueTime:'',status:'new',done:false,history:[]},
    {id:2,title:'Подобрать кассу и эквайринг',client:'Новый клиент',priority:'deferred',dueDate:'',dueTime:'',status:'waiting',done:false,history:[]},
    {id:3,title:'Проверить квитанции по двум ИП',client:'Два ИП',priority:'high',dueDate:todayIso(),dueTime:'',status:'new',done:false,history:[]}
  ]),
  rules:load('nv_rules',[
    {id:1,title:'Электронная подпись',description:'Срок 13 месяцев. Напомнить за 60, 30, 14 и 7 дней.'},
    {id:2,title:'Оплата налогов',description:'Срок 28 числа. Если выходной — следующий рабочий день.'},
    {id:3,title:'Лизинговый платеж',description:'Оплатить заранее до предыдущего рабочего дня.'}
  ])
};
state.tasks=state.tasks.map(t=>({...t,dueDate:t.dueDate||'',dueTime:t.dueTime||'',status:t.status||(t.done?'done':'new'),history:Array.isArray(t.history)?t.history:[]}));
function save(){localStorage.setItem('nv_clients',JSON.stringify(state.clients));localStorage.setItem('nv_tasks',JSON.stringify(state.tasks));localStorage.setItem('nv_rules',JSON.stringify(state.rules))}
const titles={today:['Сегодня','Что требует внимания прямо сейчас'],clients:['Клиенты',`${state.clients.length} клиентов из СБИС и ручного ввода`],tasks:['Задачи','Сроки, приоритеты и выполнение'],rules:['Правила','Повторяющиеся события и напоминания']};
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.getElementById(id).classList.add('active');document.getElementById('page-title').textContent=titles[id][0];document.getElementById('page-subtitle').textContent=id==='clients'?`${state.clients.length} клиентов из СБИС и ручного ввода`:titles[id][1];renderAll()}
window.showPage=showPage;document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>showPage(btn.dataset.page)));
function badge(p){const names={critical:'Критично',high:'Высокий',deferred:'Отложено',done:'Выполнено',overdue:'Просрочено'};return `<span class="badge ${p}">${names[p]||p}</span>`}
function formatDate(date){if(!date)return 'Без срока';return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(date+'T00:00:00'))}
function isOverdue(t){return !t.done&&t.dueDate&&t.dueDate<todayIso()}
function dueText(t){return `${formatDate(t.dueDate)}${t.dueTime?' · '+t.dueTime:''}`}
function taskSort(a,b){if(a.done!==b.done)return a.done?1:-1;if(isOverdue(a)!==isOverdue(b))return isOverdue(a)?-1:1;const pa={critical:0,high:1,deferred:2};if((pa[a.priority]??9)!==(pa[b.priority]??9))return(pa[a.priority]??9)-(pa[b.priority]??9);return(a.dueDate||'9999-12-31').localeCompare(b.dueDate||'9999-12-31')}
function taskHtml(t){const visual=t.done?'done':(isOverdue(t)?'overdue':t.priority);return `<div class="task-item ${t.done?'done':''}"><div><b>${escapeHtml(t.title)}</b><div class="meta">${escapeHtml(t.client||'Без клиента')} · ${dueText(t)}</div>${t.status==='waiting'?'<div class="meta">Ожидание</div>':''}</div><div>${badge(visual)}<div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end"><button class="link-btn" onclick="editTask(${JSON.stringify(t.id)})">Изменить</button>${!t.done?`<button class="link-btn" onclick="postponeTask(${JSON.stringify(t.id)})">Перенести</button>`:''}<button class="link-btn" onclick="toggleTask(${JSON.stringify(t.id)})">${t.done?'Вернуть':'Готово'}</button></div></div></div>`}
function renderToday(){const active=state.tasks.filter(t=>!t.done);document.getElementById('critical-count').textContent=active.filter(t=>t.priority==='critical'||isOverdue(t)).length;document.getElementById('high-count').textContent=active.filter(t=>t.priority==='high').length;document.getElementById('deferred-count').textContent=active.filter(t=>t.priority==='deferred'||t.status==='waiting').length;document.getElementById('done-count').textContent=state.tasks.filter(t=>t.done).length;const todayTasks=active.filter(t=>!t.dueDate||t.dueDate<=todayIso()).sort(taskSort);document.getElementById('today-list').innerHTML=todayTasks.slice(0,7).map(taskHtml).join('')||'<p class="meta">Срочных задач нет</p>';document.getElementById('reminder-list').innerHTML=state.rules.slice(0,4).map(r=>`<div class="rule-card"><b>${escapeHtml(r.title)}</b><div class="meta">${escapeHtml(r.description)}</div></div>`).join('')}
function renderTasks(){const f=document.getElementById('task-filter')?.value||'all';const rows=state.tasks.filter(t=>f==='all'||(f==='done'?t.done:(f==='deferred'?!t.done&&(t.priority==='deferred'||t.status==='waiting'):!t.done&&t.priority===f))).sort(taskSort);document.getElementById('tasks-list').innerHTML=rows.map(taskHtml).join('')||'<p class="meta">Задач нет</p>'}
function clientSearchText(c){return [c.name,c.inn,c.kpp,c.contractNumber,c.accountant,c.tax,c.status].join(' ').toLowerCase()}
function renderClients(){const q=(document.getElementById('client-search')?.value||'').toLowerCase().trim();const rows=state.clients.filter(c=>clientSearchText(c).includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'ru'));document.getElementById('clients-list').innerHTML=rows.map(c=>`<div class="client-row"><div><b>${escapeHtml(c.name)}</b><div class="meta">ИНН ${escapeHtml(c.inn||'не указан')}${c.kpp?' · КПП '+escapeHtml(c.kpp):''}</div></div><div><b>Договор №${escapeHtml(c.contractNumber||'—')}</b><div class="meta">от ${formatDate(c.contractDate)}</div></div><div>${escapeHtml(c.accountant||'Не назначен')}</div><div>${escapeHtml(c.status||'В работе')}</div></div>`).join('')||'<p class="meta">Клиенты не найдены</p>'}
function renderRules(){document.getElementById('rules-list').innerHTML=state.rules.map(r=>`<article class="rule-card"><b>${escapeHtml(r.title)}</b><div class="meta">${escapeHtml(r.description)}</div></article>`).join('')}
function renderAll(){renderToday();renderTasks();renderClients();renderRules()}
window.toggleTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t){t.done=!t.done;t.status=t.done?'done':'new';t.history.push({at:new Date().toISOString(),action:t.done?'Выполнена':'Возвращена в работу'});save();renderAll()}};
window.postponeTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(!t)return;const choice=prompt('Введите новую дату в формате ГГГГ-ММ-ДД',t.dueDate||todayIso());if(!choice)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(choice)){alert('Неверный формат даты');return}const old=t.dueDate;t.dueDate=choice;t.history.push({at:new Date().toISOString(),action:`Срок перенесён с ${old?formatDate(old):'без срока'} на ${formatDate(choice)}`});save();renderAll()};
document.getElementById('task-filter').addEventListener('change',renderTasks);document.getElementById('client-search').addEventListener('input',renderClients);
const modal=document.getElementById('modal'),form=document.getElementById('modal-form');
function taskFormHtml(t={}){return `<div class="field"><label>Задача</label><input name="title" required value="${escapeHtml(t.title||'')}"></div><div class="field"><label>Клиент</label><input name="client" list="client-options" value="${escapeHtml(t.client||'')}"><datalist id="client-options">${state.clients.map(c=>`<option value="${escapeHtml(c.name)}">`).join('')}</datalist></div><div class="field"><label>Приоритет</label><select name="priority"><option value="critical" ${t.priority==='critical'?'selected':''}>Критично</option><option value="high" ${t.priority==='high'?'selected':''}>Высокий</option><option value="deferred" ${t.priority==='deferred'?'selected':''}>Отложено</option></select></div><div class="field"><label>Дата исполнения</label><input type="date" name="dueDate" value="${t.dueDate||todayIso()}"></div><div class="field"><label>Время исполнения</label><input type="time" name="dueTime" value="${t.dueTime||''}"></div><div class="field"><label>Статус</label><select name="status"><option value="new" ${t.status==='new'?'selected':''}>Новая</option><option value="work" ${t.status==='work'?'selected':''}>В работе</option><option value="waiting" ${t.status==='waiting'?'selected':''}>Ожидает</option></select></div>`}
function openModal(type,entity=null){modal.classList.add('open');modal.setAttribute('aria-hidden','false');if(type==='task'){document.getElementById('modal-title').textContent=entity?'Редактирование задачи':'Новая задача';form.innerHTML=taskFormHtml(entity||{})+`<div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);if(entity){const oldDate=entity.dueDate;Object.assign(entity,{title:d.get('title'),client:d.get('client'),priority:d.get('priority'),dueDate:d.get('dueDate'),dueTime:d.get('dueTime'),status:d.get('status'),done:false});entity.history.push({at:new Date().toISOString(),action:oldDate!==entity.dueDate?`Срок изменён с ${oldDate?formatDate(oldDate):'без срока'} на ${entity.dueDate?formatDate(entity.dueDate):'без срока'}`:'Задача отредактирована'})}else state.tasks.push({id:Date.now(),title:d.get('title'),client:d.get('client'),priority:d.get('priority'),dueDate:d.get('dueDate'),dueTime:d.get('dueTime'),status:d.get('status'),done:false,history:[{at:new Date().toISOString(),action:'Создана'}]});save();closeModal();renderAll()}}
if(type==='client'){document.getElementById('modal-title').textContent='Новый клиент';form.innerHTML=`<div class="field"><label>Название</label><input name="name" required></div><div class="field"><label>ИНН</label><input name="inn"></div><div class="field"><label>КПП</label><input name="kpp"></div><div class="field"><label>Номер договора</label><input name="contractNumber"></div><div class="field"><label>Дата договора</label><input type="date" name="contractDate"></div><div class="field"><label>СНО</label><input name="tax" value="Не заполнено"></div><div class="field"><label>Ответственный</label><input name="accountant" value="Не назначен"></div><div class="field"><label>Статус</label><select name="status"><option>В работе</option><option>Новый</option><option>Риск</option></select></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);state.clients.push({id:Date.now(),name:d.get('name'),inn:d.get('inn'),kpp:d.get('kpp'),contractNumber:d.get('contractNumber'),contractDate:d.get('contractDate'),tax:d.get('tax'),accountant:d.get('accountant'),status:d.get('status'),source:'Ручной ввод'});save();closeModal();renderAll()}}
if(type==='rule'){document.getElementById('modal-title').textContent='Новое правило';form.innerHTML=`<div class="field"><label>Название</label><input name="title" required></div><div class="field"><label>Описание правила</label><textarea name="description" rows="5" required></textarea></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);state.rules.push({id:Date.now(),title:d.get('title'),description:d.get('description')});save();closeModal();renderAll()}}}
window.editTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t)openModal('task',t)};function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}window.closeModal=closeModal;document.getElementById('close-modal').onclick=closeModal;document.getElementById('quick-add').onclick=()=>openModal('task');document.getElementById('add-task').onclick=()=>openModal('task');document.getElementById('add-client').onclick=()=>openModal('client');document.getElementById('add-rule').onclick=()=>openModal('rule');modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});save();renderAll();
