const importedClients=[];
const defaultChecklist=['Выписка банка','Кассовые документы','Реализация','Покупки','Табель','Путевые листы','Авансовые отчеты','Акты сверки'];
const todayIso=()=>new Date().toISOString().slice(0,10);
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const norm=v=>String(v||'').toLowerCase().replace(/[«»"'.,]/g,'').replace(/\s+/g,' ').trim();
function mergeClients(saved){const out=[...(Array.isArray(saved)?saved:[])];importedClients.forEach(x=>{let e=out.find(c=>(c.inn&&c.inn===x.inn)||(!c.inn&&norm(c.name)===norm(x.name)));if(e)Object.entries(x).forEach(([k,v])=>{if(!e[k]||['Не заполнено','Не назначен'].includes(e[k]))e[k]=v});else out.push(x)});return out.map(c=>{const signatures=Array.isArray(c.signatures)?c.signatures:[];(window.NV_ECP_IMPORT||[]).filter(s=>s.clientId===c.id).forEach(s=>{if(!signatures.some(old=>old.id===s.id))signatures.push({...s})});return {...c,signatures,checklist:Array.isArray(c.checklist)?c.checklist:defaultChecklist.map((name,i)=>({id:i+1,name,status:'missing'})),knowledge:Array.isArray(c.knowledge)?c.knowledge:[],history:Array.isArray(c.history)?c.history:[],documents:Array.isArray(c.documents)?c.documents:[]}})}
const state={clients:mergeClients(load('nv_clients',[])),tasks:load('nv_tasks',[]),rules:load('nv_rules',[{id:1,title:'Электронная подпись',description:'Срок 13 месяцев. Напомнить заранее.'},{id:2,title:'Оплата налогов',description:'Срок 28 числа с учетом рабочих дней.'}]),unmatchedSignatures:[],activeClientId:null};
state.tasks=state.tasks.map(t=>({...t,dueDate:t.dueDate||'',dueTime:t.dueTime||'',assignee:t.assignee||'',plannedHours:Number(t.plannedHours)||0,actualHours:Number(t.actualHours)||0,status:t.status||(t.done?'done':'new'),history:Array.isArray(t.history)?t.history:[]}));
function save(){localStorage.setItem('nv_clients',JSON.stringify(state.clients));localStorage.setItem('nv_tasks',JSON.stringify(state.tasks));localStorage.setItem('nv_rules',JSON.stringify(state.rules));window.NVCloud?.scheduleSave?.()}
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const fmt=d=>d?new Intl.DateTimeFormat('ru-RU').format(new Date(d+'T00:00:00')):'—';
const titles={today:['Сегодня','Что требует внимания прямо сейчас'],clients:['Клиенты','Единый список клиентов'],tasks:['Задачи','Сроки, приоритеты и выполнение'],rules:['Правила','Повторяющиеся события и напоминания'],'client-card':['Карточка клиента','Рабочее место по клиенту']};
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.getElementById(id).classList.add('active');document.getElementById('page-title').textContent=titles[id][0];document.getElementById('page-subtitle').textContent=id==='clients'?`${state.clients.length} клиентов`:titles[id][1];renderAll()}
window.showPage=showPage;document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function renderToday(){const a=state.tasks.filter(t=>!t.done);document.getElementById('critical-count').textContent=a.filter(t=>t.priority==='critical').length;document.getElementById('high-count').textContent=a.filter(t=>t.priority==='high').length;document.getElementById('deferred-count').textContent=a.filter(t=>t.priority==='deferred'||t.status==='waiting').length;document.getElementById('done-count').textContent=state.tasks.filter(t=>t.done).length;document.getElementById('today-list').innerHTML=a.slice(0,6).map(taskHtml).join('')||'<p class="meta">Срочных задач нет</p>';const review=state.unmatchedSignatures.length?`<div class="rule-card review-card"><b>ЭЦП требуют уточнения: ${state.unmatchedSignatures.length}</b>${state.unmatchedSignatures.map(s=>`<div class="meta">${esc(s.owner)} · до ${fmt(s.expiryDate)}<br>${esc(s.reviewReason)}</div>`).join('')}</div>`:'';document.getElementById('reminder-list').innerHTML=review+state.rules.map(r=>`<div class="rule-card"><b>${esc(r.title)}</b><div class="meta">${esc(r.description)}</div></div>`).join('')}
function taskHtml(t){const hours=t.plannedHours||t.actualHours?` · Время: ${Number(t.actualHours||0)} / ${Number(t.plannedHours||0)} ч`:'';return `<div class="task-item ${t.done?'done':''}"><div><b>${esc(t.title)}</b><div class="meta">${esc(t.client||'Без клиента')} · ${fmt(t.dueDate)} ${esc(t.dueTime||'')}</div><div class="meta">Ответственный: ${esc(t.assignee||'не назначен')}${hours}</div></div><div><span class="badge ${t.done?'done':t.priority}">${t.done?'Выполнено':t.priority==='critical'?'Критично':t.priority==='high'?'Высокий':'Отложено'}</span><div style="margin-top:8px"><button class="link-btn" onclick="editTask('${t.id}')">Изменить</button><button class="link-btn" onclick="toggleTask('${t.id}')">${t.done?'Вернуть':'Готово'}</button></div></div></div>`}
function renderTasks(){const f=document.getElementById('task-filter')?.value||'all';const rows=state.tasks.filter(t=>f==='all'||(f==='done'?t.done:!t.done&&t.priority===f));document.getElementById('tasks-list').innerHTML=rows.map(taskHtml).join('')||'<p class="meta">Задач нет</p>'}
function renderClients(){const q=(document.getElementById('client-search')?.value||'').toLowerCase();const rows=state.clients.filter(c=>[c.name,c.inn,c.kpp,c.accountant,c.tax].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'ru'));document.getElementById('clients-list').innerHTML=rows.map(c=>`<div class="client-row" onclick="openClient('${c.id}')"><div><b>${esc(c.name)}</b><div class="meta">ИНН ${esc(c.inn||'—')}${c.kpp?' · КПП '+esc(c.kpp):''}</div></div><div><b>Договор №${esc(c.contractNumber||'—')}</b><div class="meta">от ${fmt(c.contractDate)}</div></div><div>${esc(c.accountant)}</div><div>${esc(c.status)}</div></div>`).join('')||'<p class="meta">Клиенты не найдены</p>'}
function renderRules(){document.getElementById('rules-list').innerHTML=state.rules.map(r=>`<article class="rule-card"><b>${esc(r.title)}</b><div class="meta">${esc(r.description)}</div></article>`).join('')}
function openClient(id){state.activeClientId=id;showPage('client-card')}window.openClient=openClient;
function renderClientCard(){const root=document.getElementById('client-card-content');if(!root)return;const c=state.clients.find(x=>String(x.id)===String(state.activeClientId));if(!c){root.innerHTML='<div class="empty-state">Клиент не выбран</div>';return}const ct=state.tasks.filter(t=>norm(t.client)===norm(c.name));const got=c.checklist.filter(x=>x.status==='received'||x.status==='not-needed').length;const pct=Math.round(got/c.checklist.length*100)||0;root.innerHTML=`
<div class="client-head"><div class="client-head-top"><div class="client-title"><h2>${esc(c.name)}</h2><p>ИНН ${esc(c.inn||'—')}${c.kpp?' · КПП '+esc(c.kpp):''}</p></div><div><button class="secondary" onclick="editClient('${c.id}')">Редактировать</button><button class="primary" onclick="newTaskForClient('${c.id}')">+ Задача</button></div></div><div class="client-summary"><div class="summary-box"><span>Статус</span><strong>${esc(c.status)}</strong></div><div class="summary-box"><span>Ответственный</span><strong>${esc(c.accountant)}</strong></div><div class="summary-box"><span>СНО</span><strong>${esc(c.tax)}</strong></div><div class="summary-box"><span>Документы</span><strong>${pct}% готово</strong></div></div></div>
<div class="client-tabs">${['overview','checklist','tasks','documents','knowledge','history'].map((x,i)=>`<button class="client-tab ${i===0?'active':''}" data-tab="${x}" onclick="switchClientTab('${x}',this)">${({overview:'Обзор',checklist:'Чек-лист',tasks:'Задачи',documents:'Документы',knowledge:'База знаний',history:'История'})[x]}</button>`).join('')}</div>
<div class="client-panel active" id="cp-overview"><section class="card"><div class="card-head"><h3>Общая информация</h3></div><div class="info-grid"><div class="info-item"><span>Наименование</span><b>${esc(c.name)}</b></div><div class="info-item"><span>ИНН / КПП</span><b>${esc(c.inn||'—')} / ${esc(c.kpp||'—')}</b></div><div class="info-item"><span>Форма бизнеса</span><b>${esc(c.legalForm||'Не заполнено')}</b></div><div class="info-item"><span>Система налогообложения</span><b>${esc(c.tax||'Не заполнено')}</b></div><div class="info-item"><span>Сотрудники</span><b>${c.hasEmployees?'Есть':'Нет / не указано'}</b></div><div class="info-item"><span>НДС</span><b>${c.vatPayer?'Плательщик':'Нет / не указано'}</b></div><div class="info-item"><span>Договор</span><b>№ ${esc(c.contractNumber||'—')} от ${fmt(c.contractDate)}</b></div><div class="info-item"><span>Источник</span><b>${esc(c.source||'Ручной ввод')}</b></div><div class="info-item"><span>Ответственный бухгалтер</span><b>${esc(c.accountant)}</b></div><div class="info-item"><span>Стоимость обслуживания</span><b>${c.servicePrice?Number(c.servicePrice).toLocaleString('ru-RU')+' ₽':'Не заполнено'}</b></div></div></section></div>
<div class="client-panel" id="cp-checklist"><section class="card"><div class="card-head"><h3>Документы за текущий период</h3><b>${pct}%</b></div><div class="check-progress"><i style="width:${pct}%"></i></div>${c.checklist.map(x=>`<div class="check-row"><b>${esc(x.name)}</b><select onchange="setChecklistStatus('${c.id}',${x.id},this.value)"><option value="missing" ${x.status==='missing'?'selected':''}>Отсутствует</option><option value="requested" ${x.status==='requested'?'selected':''}>Запрошено</option><option value="received" ${x.status==='received'?'selected':''}>Получено</option><option value="not-needed" ${x.status==='not-needed'?'selected':''}>Не требуется</option></select>${x.status==='missing'?`<button class="link-btn" onclick="createChecklistTask('${c.id}',${x.id})">Создать задачу</button>`:''}</div>`).join('')}</section></div>
<div class="client-panel" id="cp-tasks"><section class="card"><div class="card-head"><h3>Задачи клиента</h3><button class="primary" onclick="newTaskForClient('${c.id}')">+ Задача</button></div>${ct.map(taskHtml).join('')||'<div class="empty-state">Задач пока нет</div>'}</section></div>
<div class="client-panel" id="cp-documents"><section class="card"><div class="card-head"><h3>Документы и договоры</h3><button class="primary" onclick="addDocument('${c.id}')">+ Документ</button></div><div class="document-row"><b>Договор №${esc(c.contractNumber||'—')}</b><div class="meta">Дата: ${fmt(c.contractDate)}</div></div>${c.documents.map(d=>`<div class="document-row"><b>${esc(d.title)}</b><div class="meta">${esc(d.comment||'')}</div></div>`).join('')}</section></div>
<div class="client-panel" id="cp-knowledge"><section class="card"><div class="card-head"><h3>База знаний клиента</h3><button class="primary" onclick="addKnowledge('${c.id}')">+ Запись</button></div>${c.knowledge.map(n=>`<div class="knowledge-note">${esc(n.text)}</div>`).join('')||'<div class="empty-state">Особенности клиента пока не записаны</div>'}</section></div>
<div class="client-panel" id="cp-history"><section class="card"><h3>История работы</h3>${[...c.history].reverse().map(h=>`<div class="history-row"><time>${new Date(h.at).toLocaleString('ru-RU')}</time>${esc(h.text)}</div>`).join('')||'<div class="empty-state">История пока пуста</div>'}</section></div>`}
function switchClientTab(tab,btn){document.querySelectorAll('.client-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.client-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('cp-'+tab).classList.add('active')}window.switchClientTab=switchClientTab;
function setChecklistStatus(cid,i,status){const c=state.clients.find(x=>String(x.id)===String(cid));const item=c?.checklist.find(x=>x.id===i);if(item){item.status=status;c.history.push({at:new Date().toISOString(),text:`Документ «${item.name}»: ${status}`});save();renderClientCard()}}window.setChecklistStatus=setChecklistStatus;
function createChecklistTask(cid,i){const c=state.clients.find(x=>String(x.id)===String(cid));const item=c?.checklist.find(x=>x.id===i);if(!item)return;state.tasks.push({id:Date.now(),title:`Запросить: ${item.name}`,client:c.name,priority:'high',dueDate:todayIso(),dueTime:'',status:'new',done:false,history:[]});item.status='requested';c.history.push({at:new Date().toISOString(),text:`Создана задача по документу «${item.name}»`});save();renderClientCard()}window.createChecklistTask=createChecklistTask;
function addKnowledge(cid){const c=state.clients.find(x=>String(x.id)===String(cid));const text=prompt('Введите особенность или комментарий по клиенту');if(c&&text){c.knowledge.push({id:Date.now(),text});c.history.push({at:new Date().toISOString(),text:'Добавлена запись в базу знаний'});save();renderClientCard()}}window.addKnowledge=addKnowledge;
function addDocument(cid){const c=state.clients.find(x=>String(x.id)===String(cid));const title=prompt('Название документа');if(c&&title){const comment=prompt('Комментарий к документу')||'';c.documents.push({id:Date.now(),title,comment});c.history.push({at:new Date().toISOString(),text:`Добавлен документ «${title}»`});save();renderClientCard()}}window.addDocument=addDocument;
function newTaskForClient(cid){const c=state.clients.find(x=>String(x.id)===String(cid));openTaskModal(null,c?.name||'')}window.newTaskForClient=newTaskForClient;
window.toggleTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t){t.done=!t.done;t.status=t.done?'done':'new';save();renderAll()}};
const modal=document.getElementById('modal'),form=document.getElementById('modal-form');
function closeModal(){modal.classList.remove('open')}window.closeModal=closeModal;document.getElementById('close-modal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
function openTaskModal(entity=null,clientName=''){const selected=entity?.client||clientName||'';const known=state.clients.some(c=>c.name===selected);const options=state.clients.slice().sort((a,b)=>a.name.localeCompare(b.name,'ru')).map(c=>`<option value="${esc(c.name)}" ${c.name===selected?'selected':''}>${esc(c.name)}</option>`).join('');const employees=[...new Set(state.clients.flatMap(c=>[c.accountant,...(c.team||[]).flatMap(x=>[x.executor,x.reviewer,x.substitute])]).filter(x=>x&&!['Не назначен','Не заполнено'].includes(x)))].sort((a,b)=>a.localeCompare(b,'ru'));const employeeOptions=employees.map(x=>`<option value="${esc(x)}" ${x===entity?.assignee?'selected':''}>${esc(x)}</option>`).join('');modal.classList.add('open');document.getElementById('modal-title').textContent=entity?'Редактирование задачи':'Новая задача';form.innerHTML=`<div class="field"><label>Задача</label><input name="title" required value="${esc(entity?.title||'')}"></div><div class="field"><label>Клиент</label><select name="client"><option value="">Без клиента</option>${!known&&selected?`<option value="${esc(selected)}" selected>${esc(selected)}</option>`:''}${options}</select></div><div class="field"><label>Ответственный</label><select name="assignee"><option value="">Не назначен</option>${entity?.assignee&&!employees.includes(entity.assignee)?`<option selected value="${esc(entity.assignee)}">${esc(entity.assignee)}</option>`:''}${employeeOptions}</select></div><div class="field"><label>Плановое время, часов</label><input name="plannedHours" type="number" min="0" step="0.25" value="${esc(entity?.plannedHours||'')}"></div><div class="field"><label>Фактическое время, часов</label><input name="actualHours" type="number" min="0" step="0.25" value="${esc(entity?.actualHours||'')}"></div><div class="field"><label>Приоритет</label><select name="priority"><option value="critical" ${entity?.priority==='critical'?'selected':''}>Критично</option><option value="high" ${!entity||entity.priority==='high'?'selected':''}>Высокий</option><option value="deferred" ${entity?.priority==='deferred'?'selected':''}>Отложено</option></select></div><div class="field"><label>Дата исполнения</label><input type="date" name="dueDate" value="${entity?.dueDate||todayIso()}"></div><div class="field"><label>Время</label><input type="time" name="dueTime" value="${entity?.dueTime||''}"></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form),values={title:d.get('title'),client:d.get('client'),assignee:d.get('assignee'),plannedHours:Number(d.get('plannedHours'))||0,actualHours:Number(d.get('actualHours'))||0,priority:d.get('priority'),dueDate:d.get('dueDate'),dueTime:d.get('dueTime')};if(entity)Object.assign(entity,values);else state.tasks.push({id:Date.now(),...values,status:'new',done:false,history:[]});save();closeModal();renderAll()}}
window.editTask=id=>{const t=state.tasks.find(x=>String(x.id)===String(id));if(t)openTaskModal(t)};
function editClient(id){const existing=state.clients.find(x=>String(x.id)===String(id));const c=existing||{id:`manual-${Date.now()}`,name:'',inn:'',kpp:'',tax:'Не заполнено',accountant:'Не назначен',servicePrice:'',status:'В работе',source:'Ручной ввод',signatures:[],checklist:defaultChecklist.map((name,i)=>({id:i+1,name,status:'missing'})),knowledge:[],history:[],documents:[]};modal.classList.add('open');document.getElementById('modal-title').textContent=existing?'Редактирование клиента':'Новый клиент';form.innerHTML=`<div class="field"><label>Наименование</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>ИНН</label><input name="inn" value="${esc(c.inn)}"></div><div class="field"><label>СНО</label><input name="tax" value="${esc(c.tax)}"></div><div class="field"><label>Ответственный</label><input name="accountant" value="${esc(c.accountant)}"></div><div class="field"><label>Стоимость обслуживания</label><input type="number" name="servicePrice" value="${esc(c.servicePrice||'')}"></div><div class="field"><label>Статус</label><select name="status"><option>В работе</option><option>Новый</option><option>Приостановлен</option><option>Расторгнут</option></select></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div>`;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);Object.assign(c,{name:d.get('name'),inn:d.get('inn'),tax:d.get('tax'),accountant:d.get('accountant'),servicePrice:d.get('servicePrice'),status:d.get('status')});if(!existing)state.clients.push(c);c.history.push({at:new Date().toISOString(),text:existing?'Карточка клиента отредактирована':'Карточка клиента создана'});save();closeModal();renderAll()}}window.editClient=editClient;
function renderAll(){renderToday();renderTasks();renderClients();renderRules();renderClientCard()}
window.nvState=state;
window.nvApplyCloudState=function(remote){if(!remote||typeof remote!=='object')return;state.clients=mergeClients(remote.clients||state.clients);state.tasks=Array.isArray(remote.tasks)?remote.tasks:state.tasks;state.rules=Array.isArray(remote.rules)?remote.rules:state.rules;state.unmatchedSignatures=Array.isArray(remote.unmatchedSignatures)?remote.unmatchedSignatures:[];state.tasks=state.tasks.map(t=>({...t,dueDate:t.dueDate||'',dueTime:t.dueTime||'',assignee:t.assignee||'',plannedHours:Number(t.plannedHours)||0,actualHours:Number(t.actualHours)||0,status:t.status||(t.done?'done':'new'),history:Array.isArray(t.history)?t.history:[]}));window.ensureAllSignatureTasks?.();window.ensureTaxCalendar?.();save();renderAll()};
document.getElementById('client-search').oninput=renderClients;document.getElementById('task-filter').onchange=renderTasks;document.getElementById('quick-add').onclick=()=>openTaskModal();document.getElementById('add-task').onclick=()=>openTaskModal();document.getElementById('add-client').onclick=()=>editClient({});document.getElementById('add-rule').onclick=()=>alert('Добавление правил будет в следующем обновлении');const backToClients=document.getElementById('back-to-clients');if(backToClients)backToClients.onclick=()=>showPage('clients');
save();renderAll();

function taxDate(y,m,d){return new Date(Date.UTC(y,m-1,d))}
function taxIso(d){return d.toISOString().slice(0,10)}
function taxWorkday(d){const x=new Date(d);if(x.getUTCDay()===6)x.setUTCDate(x.getUTCDate()+2);if(x.getUTCDay()===0)x.setUTCDate(x.getUTCDate()+1);return x}
function addTaxTask(c,key,title,due){const dueDate=taxIso(taxWorkday(due));if(dueDate<todayIso())return;const systemKey=`НАЛОГ:${c.id}:${key}:${dueDate}`;const old=state.tasks.find(t=>t.systemKey===systemKey);if(old)return;state.tasks.push({id:Date.now()+Math.floor(Math.random()*100000),systemKey,title:`${title} · проверить по календарю`,client:c.name,assignee:c.accountant==='Не назначен'?'':c.accountant,priority:'high',dueDate,dueTime:'',plannedHours:0,actualHours:0,status:'new',done:false,calendarDraft:true,history:[{at:new Date().toISOString(),action:'Создана автоматически по налоговому профилю'}]})}
function ensureTaxCalendar(){const y=new Date().getUTCFullYear();state.clients.forEach(c=>{if(!c.tax||c.tax==='Не заполнено')return;if(c.tax.includes('УСН')){addTaxTask(c,'usn-9m','Авансовый платёж УСН за 9 месяцев',taxDate(y,10,28));addTaxTask(c,'usn-year',`Годовой налог УСН за ${y}`,taxDate(y+1,c.legalForm==='ИП'?4:3,28))}if(c.vatPayer||c.tax==='ОСН'||c.tax.includes('+ НДС')){addTaxTask(c,'vat-q2-3','НДС: платёж 3/3 за II квартал',taxDate(y,9,28));addTaxTask(c,'vat-q3-return','Декларация по НДС за III квартал',taxDate(y,10,25));[10,11,12].forEach((m,i)=>addTaxTask(c,`vat-q3-${i+1}`,`НДС: платёж ${i+1}/3 за III квартал`,taxDate(y,m,28)))}if(c.hasEmployees){for(let m=9;m<=12;m++){addTaxTask(c,`contributions-${m}`,'Уплатить страховые взносы за предыдущий месяц',taxDate(y,m,28));addTaxTask(c,`ndfl-1-${m}`,'Уплатить НДФЛ, удержанный с 1 по 22 число',taxDate(y,m,28));addTaxTask(c,`ndfl-2-${m}`,'Уплатить НДФЛ, удержанный с 23 числа',taxDate(y,m+1,5));addTaxTask(c,`injury-${m}`,'Уплатить взносы на травматизм за предыдущий месяц',taxDate(y,m,15))}['6-НДФЛ','РСВ','ЕФС-1, раздел 2'].forEach((name,i)=>addTaxTask(c,`q3-report-${i}`,`Сдать ${name} за 9 месяцев`,taxDate(y,10,25)))}if(c.profitTax){addTaxTask(c,'profit-q3-return','Декларация по налогу на прибыль за 9 месяцев',taxDate(y,10,25));addTaxTask(c,'profit-q3-pay','Авансовый платёж по налогу на прибыль за 9 месяцев',taxDate(y,10,28))}if(c.eaesImport)for(let m=9;m<=12;m++)addTaxTask(c,`eaes-${m}`,'Проверить и уплатить НДС по импорту из ЕАЭС',taxDate(y,m,20));if(c.statisticsReporting)addTaxTask(c,'statistics','Проверить перечень форм Росстата на 2026 год',taxDate(y,9,1))});save();renderAll()}
window.ensureTaxCalendar=ensureTaxCalendar;
