(function(){
  const cfg=window.NV_CONFIG||{};
  const status=document.getElementById('sync-status');
  const loginButton=document.getElementById('sync-login');
  const passwordButton=document.getElementById('sync-password');
  const bar=document.getElementById('sync-bar');
  const sessionKey='nv_supabase_session';
  let session=loadSession(), timer=null, saving=false, pending=false, hydrating=false;

  function loadSession(){try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{return null}}
  function setStatus(text,kind=''){status.textContent=text;bar.className=`sync-bar ${kind}`.trim()}
  function snapshot(){return {version:1,clients:window.nvState.clients,tasks:window.nvState.tasks,rules:window.nvState.rules,unmatchedSignatures:window.nvState.unmatchedSignatures}}
  function authHeaders(){return {'apikey':cfg.supabasePublishableKey,'Authorization':`Bearer ${session?.access_token||cfg.supabasePublishableKey}`,'Content-Type':'application/json'}}
  async function request(path,options={}){const response=await fetch(cfg.supabaseUrl+path,{...options,headers:{...authHeaders(),...(options.headers||{})}});const body=await response.text();if(!response.ok){let error={message:`Ошибка ${response.status}`};try{if(body)error=JSON.parse(body)}catch{}throw new Error(error.msg||error.message||error.error_description||`Ошибка ${response.status}`)}if(!body)return null;return JSON.parse(body)}
  async function refresh(){if(!session?.refresh_token)return false;try{session=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});localStorage.setItem(sessionKey,JSON.stringify(session));return true}catch{logout();return false}}
  function tokenExpired(){return !session?.expires_at||session.expires_at*1000<Date.now()+60000}
  async function ensureSession(){if(!session)return false;if(tokenExpired())return refresh();return true}
  function logout(){session=null;localStorage.removeItem(sessionKey);loginButton.textContent='Войти для синхронизации';passwordButton.hidden=true;setStatus('Локальное сохранение');}
  async function bootstrap(){const [clients,signatures]=await Promise.all([request('/rest/v1/nv_clients?select=*'),request('/rest/v1/nv_signatures?select=*&order=source_row')]);const mapped=clients.map(c=>({id:c.id,name:c.name,inn:c.inn||'',kpp:c.kpp||'',contractNumber:c.contract_number||'',contractDate:c.contract_date||'',tax:c.tax||'Не заполнено',accountant:c.accountant||'Не назначен',status:c.status||'В работе',source:c.source||'СБИС',servicePrice:c.service_price||'',signatures:[],checklist:[],knowledge:[],history:[],documents:[]}));const unmatched=[];signatures.forEach(s=>{const item={id:s.id,owner:s.owner_name,company:s.company_name||'',issuer:s.authority||'',purpose:s.purpose||'',issueDate:s.issue_date,expiryDate:s.expiry_date,source:'Supabase',reviewReason:s.comment||''};const client=mapped.find(c=>c.id===s.client_id);if(client)client.signatures.push(item);else unmatched.push(item)});return {version:1,clients:mapped,tasks:[],rules:window.nvState.rules,unmatchedSignatures:unmatched}}
  async function hydrate(){if(!await ensureSession())return;hydrating=true;let ready=false;try{setStatus('Загрузка рабочих данных…');const rows=await request('/rest/v1/nv_workspace_state?id=eq.main&select=id,owner_id,data');if(!rows.length){const initial=await bootstrap();window.nvApplyCloudState(initial);await request('/rest/v1/nv_workspace_state',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({id:'main',owner_id:session.user.id,data:snapshot()})});}else if(!rows[0].owner_id){const initial=Object.keys(rows[0].data||{}).length?rows[0].data:await bootstrap();window.nvApplyCloudState(initial);await request('/rest/v1/nv_workspace_state?id=eq.main',{method:'PATCH',headers:{'Prefer':'return=minimal'},body:JSON.stringify({owner_id:session.user.id,data:snapshot(),updated_at:new Date().toISOString()})});}else{window.nvApplyCloudState(rows[0].data)}loginButton.textContent='Выйти';passwordButton.hidden=false;setStatus('Данные синхронизированы','synced');ready=true}catch(error){setStatus(`Синхронизация: ${error.message}`,'error')}finally{hydrating=false;if(ready)scheduleSave()}}
  async function saveNow(){if(hydrating||saving||!session)return;if(!await ensureSession())return;saving=true;pending=false;setStatus('Сохранение…');try{await request('/rest/v1/nv_workspace_state?id=eq.main',{method:'PATCH',headers:{'Prefer':'return=minimal'},body:JSON.stringify({data:snapshot(),updated_at:new Date().toISOString()})});setStatus('Все изменения сохранены','synced')}catch(error){setStatus(`Не удалось сохранить: ${error.message}`,'error')}finally{saving=false;if(pending)scheduleSave()}}
  function scheduleSave(){if(!session||hydrating)return;pending=true;clearTimeout(timer);timer=setTimeout(saveNow,500)}
  function openLogin(){if(session){logout();return}modal.classList.add('open');document.getElementById('modal-title').textContent='Вход в NV Office';form.innerHTML=`<p class="meta">Один и тот же логин открывает ваши рабочие данные на всех устройствах.</p><div class="field"><label>Email</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>Пароль</label><input name="password" type="password" minlength="8" required autocomplete="current-password"></div><div class="form-actions"><button type="button" class="secondary" id="signup-button">Создать доступ</button><button class="primary">Войти</button></div><p class="meta" id="login-error"></p>`;form.onsubmit=e=>{e.preventDefault();authenticate('token?grant_type=password')};document.getElementById('signup-button').onclick=()=>authenticate('signup')}
  function openPassword(){modal.classList.add('open');document.getElementById('modal-title').textContent='Новый пароль';form.innerHTML=`<p class="meta">Придумайте постоянный пароль — не менее 8 символов.</p><div class="field"><label>Новый пароль</label><input name="password" type="password" minlength="8" required autocomplete="new-password"></div><div class="field"><label>Повторите пароль</label><input name="confirm" type="password" minlength="8" required autocomplete="new-password"></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Отмена</button><button class="primary">Сохранить пароль</button></div><p class="meta" id="login-error"></p>`;form.onsubmit=async e=>{e.preventDefault();const data=new FormData(form),errorNode=document.getElementById('login-error');if(data.get('password')!==data.get('confirm')){errorNode.textContent='Пароли не совпадают';return}try{await request('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:data.get('password')})});closeModal();setStatus('Пароль изменён, данные синхронизированы','synced')}catch(error){errorNode.textContent=error.message}}}
  async function authenticate(action){const data=new FormData(form),errorNode=document.getElementById('login-error');errorNode.textContent='Проверяю…';try{const result=await request(`/auth/v1/${action}`,{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password')})});if(!result.access_token){errorNode.textContent='Проверьте почту и подтвердите адрес, затем войдите.';return}session=result;localStorage.setItem(sessionKey,JSON.stringify(session));closeModal();await hydrate()}catch(error){errorNode.textContent=error.message}}
  loginButton.onclick=openLogin;
  passwordButton.onclick=openPassword;
  window.NVCloud={scheduleSave,saveNow,hydrate};
  if(cfg.supabaseUrl&&cfg.supabasePublishableKey&&session)hydrate();
})();
